apiVersion: v1
kind: Secret
metadata:
  name: ad-bind-credentials
stringData:
  AD_ADMIN_UPN: "Admin@org.innovatech.com"
  AD_ADMIN_PASSWORD: "Welkom99!!"
  AD_USER_OU: "OU=Users,OU=innovatech,DC=org,DC=innovatech,DC=com"
  AD_USER_DOMAIN: "org.innovatech.com"
  AD_DEFAULT_PASSWORD: "Welkom99!!"
  AD_DOMAIN_NETBIOS: "INNOVATECH"
  MANAGEMENT_INSTANCE_ID: "i-034f27ba77c9a100d"
