apiVersion: v1
kind: Secret
metadata:
  name: ad-bind-credentials
stringData:
  AD_ADMIN_UPN: "Admin@ad.groupd.example.com"
  AD_ADMIN_PASSWORD: "GroupD67!skibidy_"
  AD_USER_OU: "OU=AppUsers,OU=ad,DC=ad,DC=groupd,DC=example,DC=com"
  AD_USER_DOMAIN: "ad.groupd.example.com"
  AD_DOMAIN_NETBIOS: "AD"
  MANAGEMENT_INSTANCE_ID: "i-08411e7de2690bb16"
  # Default password for new AD users (must satisfy complexity)
  AD_DEFAULT_PASSWORD: "Str0ng!Pass#2026"
