apiVersion: v1
data:
  HR_DEFAULT_PASSWORD: V2Vsa29tOTkhIQ==
  SESSION_SECRET: eHlwNGlFVDBsTzVESmNudk5XZ2FSTElDWjdRQTJWZmRHcmJvU0Jta2VzOWpxdXp3
kind: Secret
metadata:
  creationTimestamp: null
  name: backend-auth
