apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  EMPLOYEE_TABLE_NAME: "narrekappe-employees"
  EMPLOYEE_PASSWORD_TABLE_NAME: "narrekappe-employee-passwords"
  AWS_REGION: "eu-central-1"
  SQS_QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/410859982724/narrekappe-onboarding-queue"
  EC2_INSTANCE_TYPE: "t3.micro"
  AMI_SSM_PARAMETER: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
  INSTANCE_PROFILE_PREFIX: "employee-profile"
  IAM_MANAGED_POLICY_ARN: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  JOB_TTL_SECONDS: "300"
  JOB_ACTIVE_DEADLINE_SECONDS: "900"
  JOB_BACKOFF_LIMIT: "0"
  JOB_SERVICE_ACCOUNT: "job-worker-sa"
  DIRECTORY_ID: "d-9967434030"
  RDP_INITIAL_DELAY_SECONDS: "60"
  RDP_MAX_RETRIES: "10"
  RDP_RETRY_DELAY_SECONDS: "15"
  EC2_SUBNET_ID: "subnet-037dbf8a81b583ed1"
  EC2_SECURITY_GROUP_ID: "sg-068c15a540ec933e0"
  SNS_TOPIC_ARN: ""
  WORKSPACES_DIRECTORY_ID: "d-9967434030"
  WORKSPACES_BUNDLE_ID: ""
  WORKSPACES_SUBNET_IDS: ""
  S3_BUCKET: ""
  # Use DynamoDB, RDS settings unused
  DB_ENGINE: "dynamodb"
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: ""
  DB_USER: ""
